model_name: 'FNO'
if_training: True
continue_training: False
batch_size: 100
unroll_step: 20
t_train: 200
model_update: 1
filename:  ['1D_Advection_Sols_beta0.4.hdf5', '1D_Advection_Sols_beta1.0.hdf5', '1D_Advection_Sols_beta0.7.hdf5', '1D_Advection_Sols_beta2.0.hdf5'] # ['1D_Advection_Sols_beta0.4.hdf5']
single_file: True
reduced_resolution: 8
reduced_resolution_t: 5
reduced_batch: 5
epochs: 30 #500
learning_rate: 3.e-3
num_workers: 0
if_save: False
#Unet
in_channels: 1
out_channels: 1
#FNO
num_channels: 1
modes: 12
width: 20
scheduler_step: 10 # 100
scheduler_gamma: 0.5
initial_step: 1  # should be the same value to unroll_step ??
# parameter embedding
if_param_embed: False
widening_factor: 64  # 16, 48
kernel_size: 5 # 31, 3
num_params: 1
num_PrmEmb_Pre: 1 # 2, 2
num_PrmEmb_Post: 0 # 0, 0
kmax: 16
if_L1loss: 0 #1.e-3
if_train_kernel: True
if_large_kernel: False
if_ft_kernel: False
num_channels_PrmEmb: 2
PrmEmb_coeff: 5.e-2
warmup_steps: -1
if_11cnv: True
if_save_data: False
if_load_data: False
gp_coef : 0
gp_kk : 1.
if_plot: False
pino_coef: 0
if_crc: True