defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
    
args:
    model_name: 'FNO'
    if_training: False
    continue_training: False
    num_workers: 2
    batch_size: 5
    initial_step: 10
    t_train: 101
    model_update: 10
    filename: '2D_diff-react_NA_NA'
    single_file: False
    reduced_resolution: 1
    reduced_resolution_t: 1
    reduced_batch: 1
    epochs: 500
    learning_rate: 1.e-3
    scheduler_step: 100
    scheduler_gamma: 0.5
    test_ratio: 0.1
    main_loss_coef: 1.
    if_TF: True
    if_CAPE_score: False
    #Unet
    in_channels: 2
    out_channels: 2
    init_features: 32
    ar_mode: True
    pushforward: True
    unroll_step: 20
    #FNO
    num_channels: 2
    modes: 12
    width: 20
    #PINN
    seed: "0000"
    # PrmEmb
    gp_coef : 0
    gp_kk : 1.
    if_plot: False
    pino_coef: 0
    if_crc: True
    #Plotting
    plot: False
    channel_plot: 0 # Which channel/variable to be plotted
    x_min: -1
    x_max: 1
    y_min: -1
    y_max: 1
    t_min: 0
    t_max: 5
    print_interval: 50
    nr_gt_steps: 1
    lr_decay: 0.4
    neighbors: 3
    time_window: 10
    if_conditional: False
